version: "0.2"
language: en
dictionaries:
  - companies
  - computing-acronyms
  - en_us
  - en-gb
  - filetypes
  - fonts
  - fullstack
  - git
  - misc
  - networking-terms
  - npm
  - scientific-terms-us
  - softwareTerms
  - web-services
words:
  - rtfd
languageSettings:
  - languageId: javascript,typescript
    dictionaries:
      - typescript
      - node
      - npm
  - languageId: json,jsonc
    dictionaries:
      - npm
      - node
  - languageId: markdown
    dictionaries:
      - html
      - html-symbol-entities
      - npm
      - node
ignorePaths:
  - ./node_modules
  - ./.nx
  - ./.yarn
