version: "0.2"
ignorePaths:
  - env.d.ts
dictionaries:
  - companies
  - computing-acronyms
  - en_US
  - en-GB
  - filetypes
  - fonts
  - fullstack
  - misc
  - networking-terms
  - npm
  - softwareTerms
  - web-services
  - scientific-terms-us
  - git
words:
  - analyte
  - analytes
  - cas
  - casrn
  - cssmodule
  - deepcode
  - gcms
  - hplc
  - icpms
  - lcmsms
  - lims
  - passcode
  - rtfd
  - svhc
  - titrimetric
  - tsdoc
  - typecheck
languageSettings:
  - languageId: javascript,typescript
    dictionaries:
      - typescript
      - node
      - npm
  - languageId: json,jsonc
    dictionaries:
      - npm
      - node
  - languageId: markdown
    dictionaries:
      - html
      - html-symbol-entities
      - npm
      - node
